/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\frontend\\backlash.github.io\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-655231aa",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-655231aa").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6977bde4",
    path: "/bar/two.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6977bde4").then(next)
    },
  },
  {
    name: "v-0344f50f",
    path: "/bar/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0344f50f").then(next)
    },
  },
  {
    path: "/bar/index.html",
    redirect: "/bar/"
  },
  {
    name: "v-135f0cb8",
    path: "/bar/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-135f0cb8").then(next)
    },
  },
  {
    name: "v-60ce972d",
    path: "/cool/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60ce972d").then(next)
    },
  },
  {
    path: "/cool/index.html",
    redirect: "/cool/"
  },
  {
    name: "v-cf949dc4",
    path: "/cool/five.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf949dc4").then(next)
    },
  },
  {
    name: "v-60d1ca24",
    path: "/bar/one.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60d1ca24").then(next)
    },
  },
  {
    name: "v-3504ee52",
    path: "/cool/six.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3504ee52").then(next)
    },
  },
  {
    name: "v-4bb9e4ae",
    path: "/foo/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bb9e4ae").then(next)
    },
  },
  {
    path: "/foo/index.html",
    redirect: "/foo/"
  },
  {
    name: "v-371a1a78",
    path: "/foo/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-371a1a78").then(next)
    },
  },
  {
    name: "v-416ed63d",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-416ed63d").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-f9f8ad1c",
    path: "/foo/four.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f9f8ad1c").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]