/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/sun.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "_Vue驱动_",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 spa 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present backlash"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-655231aa",
      "path": "/"
    },
    {
      "title": "API接口2222",
      "frontmatter": {
        "tags": [
          "美女",
          "销售"
        ]
      },
      "regularPath": "/bar/two.html",
      "relativePath": "bar/two.md",
      "key": "v-6977bde4",
      "path": "/bar/two.html",
      "headers": [
        {
          "level": 2,
          "title": "华为CDN",
          "slug": "华为cdn"
        },
        {
          "level": 3,
          "title": "刷新华为CDN接口111  (兼容华为云腾讯云)",
          "slug": "刷新华为cdn接口111-兼容华为云腾讯云"
        },
        {
          "level": 3,
          "title": "刷新华为CDN接口222  (兼容华为云腾讯云)",
          "slug": "刷新华为cdn接口222-兼容华为云腾讯云"
        },
        {
          "level": 2,
          "title": "腾讯CDN",
          "slug": "腾讯cdn"
        },
        {
          "level": 3,
          "title": "刷新tcCDN接口111",
          "slug": "刷新tccdn接口111"
        },
        {
          "level": 3,
          "title": "刷新tcCDN接口222",
          "slug": "刷新tccdn接口222"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/bar/",
      "relativePath": "bar/README.md",
      "key": "v-0344f50f",
      "path": "/bar/"
    },
    {
      "title": "API接口333",
      "frontmatter": {},
      "regularPath": "/bar/three.html",
      "relativePath": "bar/three.md",
      "key": "v-135f0cb8",
      "path": "/bar/three.html",
      "headers": [
        {
          "level": 2,
          "title": "华为CDN",
          "slug": "华为cdn"
        },
        {
          "level": 3,
          "title": "刷新华为CDN接口111  (兼容华为云腾讯云)",
          "slug": "刷新华为cdn接口111-兼容华为云腾讯云"
        },
        {
          "level": 3,
          "title": "刷新华为CDN接口222  (兼容华为云腾讯云)",
          "slug": "刷新华为cdn接口222-兼容华为云腾讯云"
        },
        {
          "level": 2,
          "title": "腾讯CDN",
          "slug": "腾讯cdn"
        },
        {
          "level": 3,
          "title": "刷新tcCDN接口111",
          "slug": "刷新tccdn接口111"
        },
        {
          "level": 3,
          "title": "刷新tcCDN接口222",
          "slug": "刷新tccdn接口222"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/cool/",
      "relativePath": "cool/README.md",
      "key": "v-60ce972d",
      "path": "/cool/"
    },
    {
      "title": "Jenkins",
      "frontmatter": {
        "tags": [
          "cool",
          "five"
        ]
      },
      "regularPath": "/cool/five.html",
      "relativePath": "cool/five.md",
      "key": "v-cf949dc4",
      "path": "/cool/five.html",
      "headers": [
        {
          "level": 2,
          "title": "Getting started",
          "slug": "getting-started"
        },
        {
          "level": 2,
          "title": "Add your files",
          "slug": "add-your-files"
        }
      ]
    },
    {
      "title": "API接口",
      "frontmatter": {
        "tags": [
          "配置",
          "主题",
          "索引"
        ]
      },
      "regularPath": "/bar/one.html",
      "relativePath": "bar/one.md",
      "key": "v-60d1ca24",
      "path": "/bar/one.html",
      "headers": [
        {
          "level": 2,
          "title": "华为CDN",
          "slug": "华为cdn"
        },
        {
          "level": 3,
          "title": "刷新华为CDN接口111  (兼容华为云腾讯云)",
          "slug": "刷新华为cdn接口111-兼容华为云腾讯云"
        },
        {
          "level": 3,
          "title": "刷新华为CDN接口222  (兼容华为云腾讯云)",
          "slug": "刷新华为cdn接口222-兼容华为云腾讯云"
        },
        {
          "level": 2,
          "title": "腾讯CDN",
          "slug": "腾讯cdn"
        },
        {
          "level": 3,
          "title": "刷新tcCDN接口111",
          "slug": "刷新tccdn接口111"
        },
        {
          "level": 3,
          "title": "刷新tcCDN接口222",
          "slug": "刷新tccdn接口222"
        }
      ]
    },
    {
      "title": "Jenkins-six",
      "frontmatter": {
        "tags": [
          "child",
          "order",
          "like"
        ]
      },
      "regularPath": "/cool/six.html",
      "relativePath": "cool/six.md",
      "key": "v-3504ee52",
      "path": "/cool/six.html",
      "headers": [
        {
          "level": 2,
          "title": "Getting started",
          "slug": "getting-started"
        },
        {
          "level": 2,
          "title": "Add your files",
          "slug": "add-your-files"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/foo/",
      "relativePath": "foo/README.md",
      "key": "v-4bb9e4ae",
      "path": "/foo/"
    },
    {
      "frontmatter": {},
      "regularPath": "/foo/three.html",
      "relativePath": "foo/three.md",
      "key": "v-371a1a78",
      "path": "/foo/three.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-416ed63d",
      "path": "/guide/"
    },
    {
      "frontmatter": {},
      "regularPath": "/foo/four.html",
      "relativePath": "foo/four.md",
      "key": "v-f9f8ad1c",
      "path": "/foo/four.html"
    }
  ],
  "themeConfig": {
    "logo": "/sun.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "运维",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/11"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/11"
          }
        ]
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "foo",
        "link": "/foo/"
      },
      {
        "text": "bar",
        "link": "/bar/"
      },
      {
        "text": "cool",
        "link": "/cool/"
      }
    ],
    "sidebar": {
      "/bar/": [
        "",
        "one",
        "two",
        "three"
      ],
      "/foo/": [
        "",
        "three",
        "four"
      ],
      "/cool/": [
        "five",
        "six"
      ]
    }
  }
}